/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as HomestayAtChailRouteImport } from './routes/homestay-at-chail'
import { Route as HomestayAtFaguRouteImport } from './routes/homestay-at-fagu'
import { Route as HomestayAtKufriRouteImport } from './routes/homestay-at-kufri'
import { Route as HomestayAtNarkandaRouteImport } from './routes/homestay-at-narkanda'
import { Route as HomestayAtShimlaRouteImport } from './routes/homestay-at-shimla'
import { Route as HomestayAtTheogRouteImport } from './routes/homestay-at-theog'
import { Route as LocationRouteImport } from './routes/location'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as PlacesToVisitIndexRouteImport } from './routes/places-to-visit/index'
import { Route as PlacesToVisitSlugRouteImport } from './routes/places-to-visit/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const HomestayAtChailRoute = HomestayAtChailRouteImport.update({
  id: '/homestay-at-chail',
  path: '/homestay-at-chail',
  getParentRoute: () => rootRouteImport,
} as any)
const HomestayAtFaguRoute = HomestayAtFaguRouteImport.update({
  id: '/homestay-at-fagu',
  path: '/homestay-at-fagu',
  getParentRoute: () => rootRouteImport,
} as any)
const HomestayAtKufriRoute = HomestayAtKufriRouteImport.update({
  id: '/homestay-at-kufri',
  path: '/homestay-at-kufri',
  getParentRoute: () => rootRouteImport,
} as any)
const HomestayAtNarkandaRoute = HomestayAtNarkandaRouteImport.update({
  id: '/homestay-at-narkanda',
  path: '/homestay-at-narkanda',
  getParentRoute: () => rootRouteImport,
} as any)
const HomestayAtShimlaRoute = HomestayAtShimlaRouteImport.update({
  id: '/homestay-at-shimla',
  path: '/homestay-at-shimla',
  getParentRoute: () => rootRouteImport,
} as any)
const HomestayAtTheogRoute = HomestayAtTheogRouteImport.update({
  id: '/homestay-at-theog',
  path: '/homestay-at-theog',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesToVisitIndexRoute = PlacesToVisitIndexRouteImport.update({
  id: '/places-to-visit/',
  path: '/places-to-visit/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesToVisitSlugRoute = PlacesToVisitSlugRouteImport.update({
  id: '/places-to-visit/$slug',
  path: '/places-to-visit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/homestay-at-chail': typeof HomestayAtChailRoute
  '/homestay-at-fagu': typeof HomestayAtFaguRoute
  '/homestay-at-kufri': typeof HomestayAtKufriRoute
  '/homestay-at-narkanda': typeof HomestayAtNarkandaRoute
  '/homestay-at-shimla': typeof HomestayAtShimlaRoute
  '/homestay-at-theog': typeof HomestayAtTheogRoute
  '/location': typeof LocationRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rooms': typeof RoomsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/places-to-visit/$slug': typeof PlacesToVisitSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/places-to-visit/': typeof PlacesToVisitIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/homestay-at-chail': typeof HomestayAtChailRoute
  '/homestay-at-fagu': typeof HomestayAtFaguRoute
  '/homestay-at-kufri': typeof HomestayAtKufriRoute
  '/homestay-at-narkanda': typeof HomestayAtNarkandaRoute
  '/homestay-at-shimla': typeof HomestayAtShimlaRoute
  '/homestay-at-theog': typeof HomestayAtTheogRoute
  '/location': typeof LocationRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rooms': typeof RoomsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/places-to-visit/$slug': typeof PlacesToVisitSlugRoute
  '/blog': typeof BlogIndexRoute
  '/places-to-visit': typeof PlacesToVisitIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/homestay-at-chail': typeof HomestayAtChailRoute
  '/homestay-at-fagu': typeof HomestayAtFaguRoute
  '/homestay-at-kufri': typeof HomestayAtKufriRoute
  '/homestay-at-narkanda': typeof HomestayAtNarkandaRoute
  '/homestay-at-shimla': typeof HomestayAtShimlaRoute
  '/homestay-at-theog': typeof HomestayAtTheogRoute
  '/location': typeof LocationRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rooms': typeof RoomsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/places-to-visit/$slug': typeof PlacesToVisitSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/places-to-visit/': typeof PlacesToVisitIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/amenities'
    | '/contact'
    | '/gallery'
    | '/homestay-at-chail'
    | '/homestay-at-fagu'
    | '/homestay-at-kufri'
    | '/homestay-at-narkanda'
    | '/homestay-at-shimla'
    | '/homestay-at-theog'
    | '/location'
    | '/privacy-policy'
    | '/rooms'
    | '/terms-and-conditions'
    | '/blog/$slug'
    | '/places-to-visit/$slug'
    | '/blog/'
    | '/places-to-visit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/amenities'
    | '/contact'
    | '/gallery'
    | '/homestay-at-chail'
    | '/homestay-at-fagu'
    | '/homestay-at-kufri'
    | '/homestay-at-narkanda'
    | '/homestay-at-shimla'
    | '/homestay-at-theog'
    | '/location'
    | '/privacy-policy'
    | '/rooms'
    | '/terms-and-conditions'
    | '/blog/$slug'
    | '/places-to-visit/$slug'
    | '/blog'
    | '/places-to-visit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/amenities'
    | '/contact'
    | '/gallery'
    | '/homestay-at-chail'
    | '/homestay-at-fagu'
    | '/homestay-at-kufri'
    | '/homestay-at-narkanda'
    | '/homestay-at-shimla'
    | '/homestay-at-theog'
    | '/location'
    | '/privacy-policy'
    | '/rooms'
    | '/terms-and-conditions'
    | '/blog/$slug'
    | '/places-to-visit/$slug'
    | '/blog/'
    | '/places-to-visit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AmenitiesRoute: typeof AmenitiesRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  HomestayAtChailRoute: typeof HomestayAtChailRoute
  HomestayAtFaguRoute: typeof HomestayAtFaguRoute
  HomestayAtKufriRoute: typeof HomestayAtKufriRoute
  HomestayAtNarkandaRoute: typeof HomestayAtNarkandaRoute
  HomestayAtShimlaRoute: typeof HomestayAtShimlaRoute
  HomestayAtTheogRoute: typeof HomestayAtTheogRoute
  LocationRoute: typeof LocationRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RoomsRoute: typeof RoomsRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PlacesToVisitSlugRoute: typeof PlacesToVisitSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  PlacesToVisitIndexRoute: typeof PlacesToVisitIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homestay-at-chail': {
      id: '/homestay-at-chail'
      path: '/homestay-at-chail'
      fullPath: '/homestay-at-chail'
      preLoaderRoute: typeof HomestayAtChailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homestay-at-fagu': {
      id: '/homestay-at-fagu'
      path: '/homestay-at-fagu'
      fullPath: '/homestay-at-fagu'
      preLoaderRoute: typeof HomestayAtFaguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homestay-at-kufri': {
      id: '/homestay-at-kufri'
      path: '/homestay-at-kufri'
      fullPath: '/homestay-at-kufri'
      preLoaderRoute: typeof HomestayAtKufriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homestay-at-narkanda': {
      id: '/homestay-at-narkanda'
      path: '/homestay-at-narkanda'
      fullPath: '/homestay-at-narkanda'
      preLoaderRoute: typeof HomestayAtNarkandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homestay-at-shimla': {
      id: '/homestay-at-shimla'
      path: '/homestay-at-shimla'
      fullPath: '/homestay-at-shimla'
      preLoaderRoute: typeof HomestayAtShimlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homestay-at-theog': {
      id: '/homestay-at-theog'
      path: '/homestay-at-theog'
      fullPath: '/homestay-at-theog'
      preLoaderRoute: typeof HomestayAtTheogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places-to-visit/': {
      id: '/places-to-visit/'
      path: '/places-to-visit'
      fullPath: '/places-to-visit/'
      preLoaderRoute: typeof PlacesToVisitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places-to-visit/$slug': {
      id: '/places-to-visit/$slug'
      path: '/places-to-visit/$slug'
      fullPath: '/places-to-visit/$slug'
      preLoaderRoute: typeof PlacesToVisitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AmenitiesRoute: AmenitiesRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  HomestayAtChailRoute: HomestayAtChailRoute,
  HomestayAtFaguRoute: HomestayAtFaguRoute,
  HomestayAtKufriRoute: HomestayAtKufriRoute,
  HomestayAtNarkandaRoute: HomestayAtNarkandaRoute,
  HomestayAtShimlaRoute: HomestayAtShimlaRoute,
  HomestayAtTheogRoute: HomestayAtTheogRoute,
  LocationRoute: LocationRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RoomsRoute: RoomsRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  BlogSlugRoute: BlogSlugRoute,
  PlacesToVisitSlugRoute: PlacesToVisitSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  PlacesToVisitIndexRoute: PlacesToVisitIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
