/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AmenitiesRouteImport } from './routes/amenities'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as HomestayInKathotRouteImport } from './routes/homestay-in-kathot'
import { Route as HomestayInTheogRouteImport } from './routes/homestay-in-theog'
import { Route as HomestayNearChailRouteImport } from './routes/homestay-near-chail'
import { Route as HomestayNearFaguRouteImport } from './routes/homestay-near-fagu'
import { Route as HomestayNearKufriRouteImport } from './routes/homestay-near-kufri'
import { Route as HomestayNearNarkandaRouteImport } from './routes/homestay-near-narkanda'
import { Route as HomestayNearShimlaRouteImport } from './routes/homestay-near-shimla'
import { Route as LocationRouteImport } from './routes/location'
import { Route as MountainViewHomestayTheogRouteImport } from './routes/mountain-view-homestay-theog'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as PlacesToVisitIndexRouteImport } from './routes/places-to-visit/index'
import { Route as PlacesToVisitSlugRouteImport } from './routes/places-to-visit/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AmenitiesRoute = AmenitiesRouteImport.update({
  id: '/amenities',
  path: '/amenities',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const HomestayInKathotRoute = HomestayInKathotRouteImport.update({
  id: '/homestay-in-kathot',
  path: '/homestay-in-kathot',
  getParentRoute: () => rootRouteImport,
} as any)
const HomestayInTheogRoute = HomestayInTheogRouteImport.update({
  id: '/homestay-in-theog',
  path: '/homestay-in-theog',
  getParentRoute: () => rootRouteImport,
} as any)
const HomestayNearChailRoute = HomestayNearChailRouteImport.update({
  id: '/homestay-near-chail',
  path: '/homestay-near-chail',
  getParentRoute: () => rootRouteImport,
} as any)
const HomestayNearFaguRoute = HomestayNearFaguRouteImport.update({
  id: '/homestay-near-fagu',
  path: '/homestay-near-fagu',
  getParentRoute: () => rootRouteImport,
} as any)
const HomestayNearKufriRoute = HomestayNearKufriRouteImport.update({
  id: '/homestay-near-kufri',
  path: '/homestay-near-kufri',
  getParentRoute: () => rootRouteImport,
} as any)
const HomestayNearNarkandaRoute = HomestayNearNarkandaRouteImport.update({
  id: '/homestay-near-narkanda',
  path: '/homestay-near-narkanda',
  getParentRoute: () => rootRouteImport,
} as any)
const HomestayNearShimlaRoute = HomestayNearShimlaRouteImport.update({
  id: '/homestay-near-shimla',
  path: '/homestay-near-shimla',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRoute = LocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => rootRouteImport,
} as any)
const MountainViewHomestayTheogRoute =
  MountainViewHomestayTheogRouteImport.update({
    id: '/mountain-view-homestay-theog',
    path: '/mountain-view-homestay-theog',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesToVisitIndexRoute = PlacesToVisitIndexRouteImport.update({
  id: '/places-to-visit/',
  path: '/places-to-visit/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesToVisitSlugRoute = PlacesToVisitSlugRouteImport.update({
  id: '/places-to-visit/$slug',
  path: '/places-to-visit/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/homestay-in-kathot': typeof HomestayInKathotRoute
  '/homestay-in-theog': typeof HomestayInTheogRoute
  '/homestay-near-chail': typeof HomestayNearChailRoute
  '/homestay-near-fagu': typeof HomestayNearFaguRoute
  '/homestay-near-kufri': typeof HomestayNearKufriRoute
  '/homestay-near-narkanda': typeof HomestayNearNarkandaRoute
  '/homestay-near-shimla': typeof HomestayNearShimlaRoute
  '/location': typeof LocationRoute
  '/mountain-view-homestay-theog': typeof MountainViewHomestayTheogRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rooms': typeof RoomsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/places-to-visit/$slug': typeof PlacesToVisitSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/places-to-visit/': typeof PlacesToVisitIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/homestay-in-kathot': typeof HomestayInKathotRoute
  '/homestay-in-theog': typeof HomestayInTheogRoute
  '/homestay-near-chail': typeof HomestayNearChailRoute
  '/homestay-near-fagu': typeof HomestayNearFaguRoute
  '/homestay-near-kufri': typeof HomestayNearKufriRoute
  '/homestay-near-narkanda': typeof HomestayNearNarkandaRoute
  '/homestay-near-shimla': typeof HomestayNearShimlaRoute
  '/location': typeof LocationRoute
  '/mountain-view-homestay-theog': typeof MountainViewHomestayTheogRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rooms': typeof RoomsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/places-to-visit/$slug': typeof PlacesToVisitSlugRoute
  '/blog': typeof BlogIndexRoute
  '/places-to-visit': typeof PlacesToVisitIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/amenities': typeof AmenitiesRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/homestay-in-kathot': typeof HomestayInKathotRoute
  '/homestay-in-theog': typeof HomestayInTheogRoute
  '/homestay-near-chail': typeof HomestayNearChailRoute
  '/homestay-near-fagu': typeof HomestayNearFaguRoute
  '/homestay-near-kufri': typeof HomestayNearKufriRoute
  '/homestay-near-narkanda': typeof HomestayNearNarkandaRoute
  '/homestay-near-shimla': typeof HomestayNearShimlaRoute
  '/location': typeof LocationRoute
  '/mountain-view-homestay-theog': typeof MountainViewHomestayTheogRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/rooms': typeof RoomsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/places-to-visit/$slug': typeof PlacesToVisitSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/places-to-visit/': typeof PlacesToVisitIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/amenities'
    | '/contact'
    | '/gallery'
    | '/homestay-in-kathot'
    | '/homestay-in-theog'
    | '/homestay-near-chail'
    | '/homestay-near-fagu'
    | '/homestay-near-kufri'
    | '/homestay-near-narkanda'
    | '/homestay-near-shimla'
    | '/location'
    | '/mountain-view-homestay-theog'
    | '/privacy-policy'
    | '/rooms'
    | '/terms-and-conditions'
    | '/blog/$slug'
    | '/places-to-visit/$slug'
    | '/blog/'
    | '/places-to-visit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/amenities'
    | '/contact'
    | '/gallery'
    | '/homestay-in-kathot'
    | '/homestay-in-theog'
    | '/homestay-near-chail'
    | '/homestay-near-fagu'
    | '/homestay-near-kufri'
    | '/homestay-near-narkanda'
    | '/homestay-near-shimla'
    | '/location'
    | '/mountain-view-homestay-theog'
    | '/privacy-policy'
    | '/rooms'
    | '/terms-and-conditions'
    | '/blog/$slug'
    | '/places-to-visit/$slug'
    | '/blog'
    | '/places-to-visit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/amenities'
    | '/contact'
    | '/gallery'
    | '/homestay-in-kathot'
    | '/homestay-in-theog'
    | '/homestay-near-chail'
    | '/homestay-near-fagu'
    | '/homestay-near-kufri'
    | '/homestay-near-narkanda'
    | '/homestay-near-shimla'
    | '/location'
    | '/mountain-view-homestay-theog'
    | '/privacy-policy'
    | '/rooms'
    | '/terms-and-conditions'
    | '/blog/$slug'
    | '/places-to-visit/$slug'
    | '/blog/'
    | '/places-to-visit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AmenitiesRoute: typeof AmenitiesRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  HomestayInKathotRoute: typeof HomestayInKathotRoute
  HomestayInTheogRoute: typeof HomestayInTheogRoute
  HomestayNearChailRoute: typeof HomestayNearChailRoute
  HomestayNearFaguRoute: typeof HomestayNearFaguRoute
  HomestayNearKufriRoute: typeof HomestayNearKufriRoute
  HomestayNearNarkandaRoute: typeof HomestayNearNarkandaRoute
  HomestayNearShimlaRoute: typeof HomestayNearShimlaRoute
  LocationRoute: typeof LocationRoute
  MountainViewHomestayTheogRoute: typeof MountainViewHomestayTheogRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RoomsRoute: typeof RoomsRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PlacesToVisitSlugRoute: typeof PlacesToVisitSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  PlacesToVisitIndexRoute: typeof PlacesToVisitIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amenities': {
      id: '/amenities'
      path: '/amenities'
      fullPath: '/amenities'
      preLoaderRoute: typeof AmenitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homestay-in-kathot': {
      id: '/homestay-in-kathot'
      path: '/homestay-in-kathot'
      fullPath: '/homestay-in-kathot'
      preLoaderRoute: typeof HomestayInKathotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homestay-in-theog': {
      id: '/homestay-in-theog'
      path: '/homestay-in-theog'
      fullPath: '/homestay-in-theog'
      preLoaderRoute: typeof HomestayInTheogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homestay-near-chail': {
      id: '/homestay-near-chail'
      path: '/homestay-near-chail'
      fullPath: '/homestay-near-chail'
      preLoaderRoute: typeof HomestayNearChailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homestay-near-fagu': {
      id: '/homestay-near-fagu'
      path: '/homestay-near-fagu'
      fullPath: '/homestay-near-fagu'
      preLoaderRoute: typeof HomestayNearFaguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homestay-near-kufri': {
      id: '/homestay-near-kufri'
      path: '/homestay-near-kufri'
      fullPath: '/homestay-near-kufri'
      preLoaderRoute: typeof HomestayNearKufriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homestay-near-narkanda': {
      id: '/homestay-near-narkanda'
      path: '/homestay-near-narkanda'
      fullPath: '/homestay-near-narkanda'
      preLoaderRoute: typeof HomestayNearNarkandaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homestay-near-shimla': {
      id: '/homestay-near-shimla'
      path: '/homestay-near-shimla'
      fullPath: '/homestay-near-shimla'
      preLoaderRoute: typeof HomestayNearShimlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location': {
      id: '/location'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mountain-view-homestay-theog': {
      id: '/mountain-view-homestay-theog'
      path: '/mountain-view-homestay-theog'
      fullPath: '/mountain-view-homestay-theog'
      preLoaderRoute: typeof MountainViewHomestayTheogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places-to-visit/': {
      id: '/places-to-visit/'
      path: '/places-to-visit'
      fullPath: '/places-to-visit/'
      preLoaderRoute: typeof PlacesToVisitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places-to-visit/$slug': {
      id: '/places-to-visit/$slug'
      path: '/places-to-visit/$slug'
      fullPath: '/places-to-visit/$slug'
      preLoaderRoute: typeof PlacesToVisitSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AmenitiesRoute: AmenitiesRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  HomestayInKathotRoute: HomestayInKathotRoute,
  HomestayInTheogRoute: HomestayInTheogRoute,
  HomestayNearChailRoute: HomestayNearChailRoute,
  HomestayNearFaguRoute: HomestayNearFaguRoute,
  HomestayNearKufriRoute: HomestayNearKufriRoute,
  HomestayNearNarkandaRoute: HomestayNearNarkandaRoute,
  HomestayNearShimlaRoute: HomestayNearShimlaRoute,
  LocationRoute: LocationRoute,
  MountainViewHomestayTheogRoute: MountainViewHomestayTheogRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RoomsRoute: RoomsRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  BlogSlugRoute: BlogSlugRoute,
  PlacesToVisitSlugRoute: PlacesToVisitSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  PlacesToVisitIndexRoute: PlacesToVisitIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
